### ISSUE TITLE
It doesn't appear to be working...

### ISSUE THREAD

**Issue by masuteri** [GammaTick/Reusable-Vault-Blocks#1]
![{828DAEFF-7F7B-4C12-8264-138DDE4D6381}](https://github.com/user-attachments/assets/afcb1342-5d6d-405a-a876-eb4f3ac23897)
the server has been on for multiple days and doesn't appear to actually be renewing the vaults

**Comment by masuteri** [comment]
Getting the data for the block, it would seem that the time doesn't actually seem to be going down or up. 
![{AE4C8997-05A6-4EA3-B4EA-2692AB223D30}](https://github.com/user-attachments/assets/f8432c34-6d96-41e1-ac69-646b7b8f752e)

**Comment by GammaTick** [comment]
It's working as intended. It's not an actual cooldown that is ticking, rather, it shows when the cooldown is going to end. I made it this way because if I used a cooldown, the Vault block would have to be loaded all the time for the cooldown to tick down. When the world time reaches the value of the 'cooldown_ends_at' variable, the Vault block removes the player for whom the cooldown is over.

**Comment by GammaTick** [comment]
Also the cooldown for the non-ominous variant of the Vault block is 10 hours in the real world and of couse you would have to be in the world itself for the world time to increase and therefore the "cooldown" of the vault block to "tick down".

**Comment by masuteri** [comment]
Yeah no the problem is I last time opened the vault more than 40 real life hours ago and we're using your defaults

**Comment by GammaTick** [comment]
But when you opened it 40 hours ago, have you played in your world for a total of 10 hours or more since then?

**Comment by GammaTick** [comment]
I can confirm that this is a bug, when no one is on the server the Vault block increases the value of the "cooldown_ends_at" variable.

**Comment by GammaTick** [comment]
I just fixed the bug! I really want to thank you for the bug report and I'm really, really sorry for the inconvenience.
